android:
  config:
    "dynatrace {
      configurations {
        defaultConfig {
          autoStart{
            applicationId '648fa531-b919-4d94-b6cc-2aefac780749'
            beaconUrl 'https://rum.redsara.es:9999/mbeacon/38993f78-c97c-4ab5-8f9e-8df5e35f736d'
          }
          userOptIn true
          agentBehavior.startupLoadBalancing true
        }
      }
    }"

ios:
  config:
    "<key>DTXApplicationID</key>
    <string>648fa531-b919-4d94-b6cc-2aefac780749</string>
    <key>DTXBeaconURL</key>
    <string>https://rum.redsara.es:9999/mbeacon/38993f78-c97c-4ab5-8f9e-8df5e35f736d</string>
    <key>DTXUserOptIn</key>
    <true/>
    <key>DTXStartupLoadBalancing</key>
    <true/>"
