name: portafirmas_app
description: Portafirmas app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 3.2.2

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  go_router: ^6.0.1
  # Code generation
  #
  # Code-generators available to help you deal with immutable objects
  # https://pub.dev/packages/freezed
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0

  #
  # To generate to/from JSON code for a class
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: any
  # Generate native splash screen
  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  # https://pub.dev/packages/flutter_native_splash
  # flutter_native_splash: ^2.2.17

  # Dependency injection
  # https://pub.dev/packages/get_it
  get_it: ^7.2.0
  # Network
  #
  # Http Client
  # https://pub.dev/packages/dio
  dio: ^4.0.6

  # Local database
  # https://pub.dev/packages/hive
  hive: ^2.2.3

  # Dio client generator
  # https://pub.dev/packages/retrofit
  retrofit: ">=3.0.0 <4.0.0"

  # Parse xml to json
  # https://pub.dev/packages/retrofit
  xml2json: ^5.3.6

  # Encode to RSA
  # https://pub.dev/packages/fast_rsa
  fast_rsa: ^3.6.1

  # Save session id
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^7.0.1

  ## State Management
  #
  # Bloc State Management
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.0.1

  # SVG displayer
  #
  # paints and displays SVG annexes
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.5

  # Lottie animations
  #
  # renders json animations
  # https://pub.dev/packages/lottie
  lottie: ^3.0.0

  #  App factory UI widgets
  app_factory_ui:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/widgets/app-factory-ui-kit.git
      ref: mainv4

  emm:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/componentes_comunes/deteccion-emm.git
      ref: develop

  #  dependency for PDF viewer
  url_launcher: ^6.1.11
  flutter_pdfview: ^1.3.2
  open_filex: ^4.4.0

  # get native path
  #
  # A Flutter plugin for finding commonly used locations on the filesystem.
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.0
  # Webview
  #
  # WebView plugin for authentication with cl@ve
  flutter_inappwebview: ^6.0.0

  # Handle certificates
  #
  firma_portafirmas:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/componentes_comunes/libreria-portafirmas/modulo-flutter.git
      ref: feature/version-issues

  # File picker to get the certificate
  file_picker: ^8.0.0+1

  device_info: ^2.0.3
  # Push notifications
  #
  # To manage push notifications
  push_notifications:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/componentes_comunes/push-notifications.git
      ref: mainv4
  # Notification permissions
  # To handle notification permissions
  # https://pub.dev/packages/notification_permissions
  notification_permissions: ^0.6.1
  ## Dynatrace
  dynatrace:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/componentes_comunes/dynatrace.git
      ref: mainv4

  # Setup Component
  # to check current app version, update and check for root devices
  af_setup:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/componentes_comunes/setup.git
      ref: mainV4 #branch name

  # Auth Biometric login
  biometric:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/componentes_comunes/biometric-login.git
      ref: main

  af_privacy_policy:
    git:
      url: https://gitlab-ic.scae.redsara.es/app-factory/proyectos/componentes_comunes/politica-de-privacidad.git
      ref: mainv4
  flutter_html: ^3.0.0-alpha.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

  # Standalone generator
  # https://pub.dev/packages/build_runner
  build_runner: ^2.2.1

  # Http
  #
  # retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ">=4.0.0 <5.0.0"

  # Testing
  #
  # A mock framework inspired by Mockito
  # https://pub.dev/packages/mockito
  mockito: ^5.3.2
  #
  # A testing library which makes it easy to test blocs.
  # https://pub.dev/packages/bloc_test
  bloc_test: ^9.1.0

  # Generate hive models
  #
  # https://pub.dev/packages/hive_generator
  hive_generator: ^2.0.1

  # Testing path providers
  path_provider_platform_interface: ^2.1.2

  # Generate dynatrace files
  #
  # https://pub.dev/packages/dynatrace_flutter_plugin
  dynatrace_flutter_plugin: 3.283.1

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  intl: ^0.18.1
  flutter_inappwebview_ios:
    git:
      url: https://github.com/andychucs/flutter_inappwebview.git
      ref: master
      path: flutter_inappwebview_ios

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/mock/document/doc_1.pdf
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/animation/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
# flutter_native_splash:
#   background_image: lib/assets/splash/splash_screen.png
#   android_12: lib/assets/splash/splash_screen.png
#   android_gravity: fill

